<?xml version="1.0" encoding="utf-8"?>
<Database Name="tribalwars" Class="TribalWarsMappingDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DREAMINGFIGHTER\SQLEXPRESS;Initial Catalog=tribalwars;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="tribalwarsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.diplomates" Member="diplomates">
    <Type Name="diplomate">
      <Column Name="group_1" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="group_2" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Group_diplomate" Member="group" ThisKey="group_1" OtherKey="ID" Type="Group" IsForeignKey="true" />
      <Association Name="Group_diplomate1" Member="Group1" ThisKey="group_2" OtherKey="ID" Type="Group" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.groups" Member="Groups">
    <Type Name="Group">
      <Column Name="id" Member="ID" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Member="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Member="Allies" Type="System.String" CanBeNull="false" />
      <Column Member="Naps" Type="System.String" CanBeNull="false" />
      <Column Member="Enemies" Type="System.String" CanBeNull="false" />
      <Association Name="Group_diplomate" Member="diplomates" ThisKey="ID" OtherKey="group_1" Type="diplomate" />
      <Association Name="Group_diplomate1" Member="diplomates1" ThisKey="ID" OtherKey="group_2" Type="diplomate" />
      <Association Name="Group_User" Member="Users" ThisKey="ID" OtherKey="group_id" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.offers" Member="Offers">
    <Type Name="Offer">
      <Column Name="id" Member="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="offertype" Member="OfferType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="offerquantity" Member="OfferQuantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fortype" Member="ForType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="forquantity" Member="ForQuantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="offernumber" Member="OfferNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="maxtransporttime" Member="MaxTransportTime" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="village_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Village_Offer" Member="Village" ThisKey="village_id" OtherKey="ID" Type="Village" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.users" Member="Users">
    <Type Name="User">
      <Column Name="username" Member="Username" Type="System.String" DbType="NVarChar(200) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="group_id" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="sex" Member="Sex" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="birthdate" Member="Birthdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="last_update" Member="LastUpdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="User_Village" Member="Villages" ThisKey="Username" OtherKey="userid" Type="Village" />
      <Association Name="Group_User" Member="Group" ThisKey="group_id" OtherKey="ID" Type="Group" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.villages" Member="Villages">
    <Type Name="Village">
      <Column Name="id" Member="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="x" Member="X" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="y" Member="Y" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Member="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="userid" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="wood" Member="Wood" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="clay" Member="Clay" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="iron" Member="Iron" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="headquarter" Member="Headquarter" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="barracks" Member="Barracks" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="stable" Member="Stable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="workshop" Member="Workshop" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="academy" Member="Academy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="smithy" Member="Smithy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="rally" Member="Rally" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="market" Member="Market" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="timbercamp" Member="TimberCamp" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="claypit" Member="ClayPit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ironmine" Member="IronMine" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="storage" Member="Storage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="farm" Member="Farm" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hide" Member="HiddenPlace" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="wall" Member="Wall" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="points" Member="Points" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="unit_spear_tec_level" Member="SpearTechLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="unit_sword_tec_level" Member="SwordTechLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="unit_axe_tec_level" Member="AxeTechLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="unit_spy_tec_level" Member="ScoutTechLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="unit_light_tec_level" Member="LightTechLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="unit_heavy_tec_level" Member="HeavyTechLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="unit_ram_tec_level" Member="RamTechLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="unit_catapult_tec_level" Member="CatapultTechLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="all_unit_spear" Member="Spear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="all_unit_sword" Member="Sword" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="all_unit_axe" Member="Axe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="all_unit_spy" Member="Scout" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="all_unit_light" Member="Light" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="all_unit_heavy" Member="Heavy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="all_unit_ram" Member="Ram" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="all_unit_catapult" Member="Catapult" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="all_unit_snob" Member="Nobleman" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="last_update" Member="LastUpdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="loyal" Member="Loyal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Village_Offer" Member="Offers" ThisKey="ID" OtherKey="village_id" Type="Offer" />
      <Association Name="Village_movement" Member="movements" ThisKey="ID" OtherKey="From" Type="AttackTo" />
      <Association Name="Village_movement1" Member="AttackTos" ThisKey="ID" OtherKey="To" Type="AttackTo" />
      <Association Name="Village_movement2" Member="movements1" ThisKey="ID" OtherKey="From" Type="SupportTo" />
      <Association Name="Village_movement3" Member="SupportTos" ThisKey="ID" OtherKey="To" Type="SupportTo" />
      <Association Name="Village_movement4" Member="movements2" ThisKey="ID" OtherKey="From" Type="TradingTo" />
      <Association Name="Village_movement5" Member="TradingTos" ThisKey="ID" OtherKey="To" Type="TradingTo" />
      <Association Name="Village_movement6" Member="movements3" ThisKey="ID" OtherKey="From" Type="Return" />
      <Association Name="Village_movement7" Member="Returns" ThisKey="ID" OtherKey="To" Type="Return" />
      <Association Name="Village_movement8" Member="movements4" ThisKey="ID" OtherKey="From" Type="AttackFrom" />
      <Association Name="Village_movement9" Member="AttackFroms" ThisKey="ID" OtherKey="To" Type="AttackFrom" />
      <Association Name="Village_movement10" Member="movements5" ThisKey="ID" OtherKey="From" Type="SupportFrom" />
      <Association Name="Village_movement11" Member="SupportFroms" ThisKey="ID" OtherKey="To" Type="SupportFrom" />
      <Association Name="Village_movement12" Member="movements6" ThisKey="ID" OtherKey="From" Type="TradingFrom" />
      <Association Name="Village_movement13" Member="TradingFroms" ThisKey="ID" OtherKey="To" Type="TradingFrom" />
      <Association Name="User_Village" Member="User" ThisKey="userid" OtherKey="Username" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.movement" Member="AttackTos">
    <Type Name="AttackTo">
      <Column Name="id" Member="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[from]" Member="From" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[to]" Member="To" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="type" Member="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="starting_time" Member="StartingTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="landing_time" Member="LandingTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="building" Member="Building" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="scoutSent" Member="Scout" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="spearSent" Member="Spear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="swordSent" Member="Sword" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="axeSent" Member="Axe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lightSent" Member="Light" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="heavySent" Member="Heavy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ramSent" Member="Ram" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="catapultSent" Member="Catapult" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nobleSent" Member="Noble" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Village_movement" Member="Village" ThisKey="From" OtherKey="ID" Type="Village" IsForeignKey="true" />
      <Association Name="Village_movement1" Member="Village1" ThisKey="To" OtherKey="ID" Type="Village" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.movement" Member="SupportTos">
    <Type Name="SupportTo">
      <Column Name="id" Member="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[from]" Member="From" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[to]" Member="To" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="type" Member="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="starting_time" Member="StartingTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="landing_time" Member="LandingTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="scoutSent" Member="Scout" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="spearSent" Member="Spear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="swordSent" Member="Sword" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="axeSent" Member="Axe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lightSent" Member="Light" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="heavySent" Member="Heavy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ramSent" Member="Ram" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="catapultSent" Member="Catapult" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nobleSent" Member="Noble" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Village_movement2" Member="Village" ThisKey="From" OtherKey="ID" Type="Village" IsForeignKey="true" />
      <Association Name="Village_movement3" Member="Village1" ThisKey="To" OtherKey="ID" Type="Village" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.movement" Member="TradingTos">
    <Type Name="TradingTo">
      <Column Name="id" Member="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[from]" Member="From" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[to]" Member="To" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="type" Member="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="starting_time" Member="StartingTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="landing_time" Member="LandingTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="iron" Member="Iron" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="clay" Member="Clay" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="wood" Member="Wood" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Village_movement4" Member="Village" ThisKey="From" OtherKey="ID" Type="Village" IsForeignKey="true" />
      <Association Name="Village_movement5" Member="Village1" ThisKey="To" OtherKey="ID" Type="Village" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.movement" Member="Returns">
    <Type Name="Return">
      <Column Name="id" Member="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[from]" Member="From" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[to]" Member="To" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="type" Member="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="starting_time" Member="StartingTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="landing_time" Member="LandingTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="swordReturnt" Member="Sword" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="axeReturnt" Member="Axe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="scoutReturnt" Member="Scout" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lightReturnt" Member="Light" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="heavyReturnt" Member="Heavy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ramReturnt" Member="Ram" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="catapultReturnt" Member="Catapult" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nobleReturnt" Member="Noble" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="iron" Member="Iron" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="clay" Member="Clay" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="wood" Member="Wood" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Village_movement6" Member="Village" ThisKey="From" OtherKey="ID" Type="Village" IsForeignKey="true" />
      <Association Name="Village_movement7" Member="Village1" ThisKey="To" OtherKey="ID" Type="Village" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.movement" Member="AttackFroms">
    <Type Name="AttackFrom">
      <Column Name="id" Member="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[from]" Member="From" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[to]" Member="To" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="type" Member="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="starting_time" Member="StartingTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="landing_time" Member="LandingTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="building" Member="Building" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="scoutSent" Member="Scout" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="spearSent" Member="Spear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="swordSent" Member="Sword" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="axeSent" Member="Axe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lightSent" Member="Light" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="heavySent" Member="Heavy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ramSent" Member="Ram" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="catapultSent" Member="Catapult" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nobleSent" Member="Noble" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Village_movement8" Member="Village" ThisKey="From" OtherKey="ID" Type="Village" IsForeignKey="true" />
      <Association Name="Village_movement9" Member="Village1" ThisKey="To" OtherKey="ID" Type="Village" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.movement" Member="SupportFroms">
    <Type Name="SupportFrom">
      <Column Name="id" Member="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[from]" Member="From" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[to]" Member="To" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="type" Member="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="starting_time" Member="StartingTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="landing_time" Member="LandingTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="scoutSent" Member="Scout" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="spearSent" Member="Spear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="swordSent" Member="Sword" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="axeSent" Member="Axe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lightSent" Member="Light" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="heavySent" Member="Heavy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ramSent" Member="Ram" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="catapultSent" Member="Catapult" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nobleSent" Member="Noble" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Village_movement10" Member="Village" ThisKey="From" OtherKey="ID" Type="Village" IsForeignKey="true" />
      <Association Name="Village_movement11" Member="Village1" ThisKey="To" OtherKey="ID" Type="Village" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.movement" Member="TradingFroms">
    <Type Name="TradingFrom">
      <Column Name="id" Member="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[from]" Member="From" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[to]" Member="To" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="type" Member="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="starting_time" Member="StartingTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="landing_time" Member="LandingTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="iron" Member="Iron" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="clay" Member="Clay" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="wood" Member="Wood" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Village_movement12" Member="Village" ThisKey="From" OtherKey="ID" Type="Village" IsForeignKey="true" />
      <Association Name="Village_movement13" Member="Village1" ThisKey="To" OtherKey="ID" Type="Village" IsForeignKey="true" />
    </Type>
  </Table>
</Database>